[package]
name = "day20"
version = "0.1.0"
edition = "2021"

[dependencies]
fixedbitset = "0.5.7"
indicatif = { version = "0.17.9", features = ["rayon"] }
pathfinding = "4.12.0"
rayon = "1.10.0"
rustc-hash = "2.1.0"
